
services:
  db:
    container_name: aluno_api
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /data/aluno_api:/var/lib/postgresql/data
volumes:
  db: